custom_thresholds:
  AAPL.US:
    price_change: 1.5
symbols:
- RXRX270115C4000.US
- RXRX270115C3500.US
- RXRX261120C3500.US
- RXRX.US
- NVDA.US
- LEGN270115C22500.US
- LEGN.US
- SE.US
- UNH.US
- AZN.US
- GH.US
- BILI.US
- APP.US
- ASTS.US
- FXP.US
- PYPL.US
- LEGN261218C22500.US
- PLTR.US
- LEGN270115C20000.US
- AMD.US
- LEGN261218C20000.US
- LEGN261218C17500.US
- NVO.US
- ALM.US
- TTWO.US
- DSNKY.US
- MRNA.US
- BMY.US
- ABBV.US
- PFE.US
- NBIS.US
- RXRX270115C4000.US
- RXRX270115C3500.US
- RXRX261120C3500.US
- RXRX.US
- NVDA.US
- LEGN270115C22500.US
- LEGN.US
- SE.US
- UNH.US
- AZN.US
- GH.US
- BILI.US
- APP.US
- ASTS.US
- FXP.US
- PYPL.US
- LEGN261218C22500.US
- PLTR.US
- LEGN270115C20000.US
- AMD.US
- LEGN261218C20000.US
- LEGN261218C17500.US
- NVO.US
- ALM.US
- TTWO.US
- DSNKY.US
- MRNA.US
- BMY.US
- ABBV.US
- PFE.US
- NBIS.US
- RXRX270115C4000.US
- RXRX270115C3500.US
- RXRX261120C3500.US
- LEGN270115C22500.US
- LEGN261218C22500.US
- LEGN270115C20000.US
- LEGN261218C20000.US
- LEGN261218C17500.US
thresholds:
  price_change: 4.0
